# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_DB_DATABASE: ${MONGO_DB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  # blog-api:
  #   image: api-blog
  #   restart: always
  #   ports:
  #     - 4005:4005
  #   depends_on:
  #     - mongo

volumes:
  mongo-data: {}